### ISSUE TITLE
Adding scriptuRs?

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/R-text-data#12]
@andrewheiss is there anything included in your [scriptuRs package](https://github.com/andrewheiss/scriptuRs) that isn't in the [sacred package](https://github.com/JohnCoene/sacred)? 😄

**Comment by andrewheiss** [comment]
Other than the `lds_scriptures()` and `kjv_bible()` functions, nope. It's the same data source.

**Comment by EmilHvitfeldt** [comment]
Okay, I think I'm going add it anyways, it doesn't (yet) hurt to have some overlap.

**Comment by andrewheiss** [comment]
Yeah, I've been considering how to handle that. I don't want to parallel maintain quRan and sacred, but it'd be nice to have the Quran in sacred. Perhaps making some sort of central sacred text package with https://github.com/mkearney/pkgverse (á la tidyverse) that installs all these other packages (like rperseus, scriptuRs, quRan, sacred, etc.) simultaneously would be helpful. That way they can all be maintained separately, but installed at the same time?

**Comment by EmilHvitfeldt** [comment]
That might work, but could also turn into quite a pkgverse as more and more packages are added (and how do you decide that is pkgverse worthy?). I feel like having this repo being a central hub of information works okay as of now.

how often would you want to combine multiple data packages?

**Comment by EmilHvitfeldt** [comment]
I have added this package as it includes more metadata then then sacred package

**Comment by andrewheiss** [comment]
Oh, I mean a pkgverse thing for just sacred texts, not everything here in R-text-data :)
